spring:
  datasource:
    url: jdbc:mysql://localhost:3306/selforderingrestaurant
    username: ngan123
    password: ngan123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  privateKey: 5IM62UKQWiA6rAujwhuwn1XaWE6oXEI6wKKPMcVun9c=
