spring:
  datasource:
    url: jdbc:mysql://localhost:3306/selforderingrestaurant
    username: root
    password: Diepdiep@0310
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
  mvc:
    async:
      request-timeout: 30000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  websocket:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
      allow-credentials: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

jwt:
  privateKey: 5IM62UKQWiA6rAujwhuwn1XaWE6oXEI6wKKPMcVun9c=

file:
  upload-dir: uploads/images

app:
  base-url: http://localhost:8080






