spring:
  datasource:
    url: jdbc:mysql://localhost:3306/selforderingrestaurant
    username: root
    password: Diepdiep@0310
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
